/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef BG_GATTDB_H
#define BG_GATTDB_H

#include "ubt/bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define xgatt_command_byte                      8
#define xgatt_custom_string                    10
#define xgatt_temperature                      14
#define xgatt_accelerometer                    18

#endif
