/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef BG_GATTDB_H
#define BG_GATTDB_H

#include "ubt/bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define xgatt_batt_power                        8

#endif
